name: InspectCode

on:
  push:
    branches:
      - main
      - feature/document
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  inspect-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Annotate
        # You may pin to the exact commit or the version.
        uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          solution: ./Traincrew_MultiATS_Server.sln
          tool-version: 2025.2.3
          dotnetcoresdk: 8.0.x

    permissions:
      security-events: write
